#!/usr/bin/env python3
"""从 Liberation 字体提取度量，生成 font/metrics.go（标准 14 字体宽度表）。

Liberation Sans/Serif/Mono 与 Helvetica/Times/Courier（及 Arial/Times New Roman/
Courier New）度量兼容，因此提取的宽度表可作为标准 14 字体的排版依据。

用法：python3 font/genmetrics.py > font/metrics.go
仅依赖 Python 标准库，自行解析 TTF 的 head/hhea/maxp/OS2/cmap/hmtx 表。
"""
import struct

FONTS = [
    ("helveticaMetrics", "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf"),
    ("helveticaBoldMetrics", "/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf"),
    ("timesRomanMetrics", "/usr/share/fonts/truetype/liberation2/LiberationSerif-Regular.ttf"),
    ("timesBoldMetrics", "/usr/share/fonts/truetype/liberation2/LiberationSerif-Bold.ttf"),
    ("timesItalicMetrics", "/usr/share/fonts/truetype/liberation2/LiberationSerif-Italic.ttf"),
    ("timesBoldItalicMetrics", "/usr/share/fonts/truetype/liberation2/LiberationSerif-BoldItalic.ttf"),
    ("courierMetrics", "/usr/share/fonts/truetype/liberation2/LiberationMono-Regular.ttf"),
]

# WinAnsiEncoding 0x80-0x9F 区间：字节 -> Unicode
WINANSI_EXTRA = {
    0x80: 0x20AC, 0x82: 0x201A, 0x83: 0x0192, 0x84: 0x201E, 0x85: 0x2026,
    0x86: 0x2020, 0x87: 0x2021, 0x88: 0x02C6, 0x89: 0x2030, 0x8A: 0x0160,
    0x8B: 0x2039, 0x8C: 0x0152, 0x8E: 0x017D, 0x91: 0x2018, 0x92: 0x2019,
    0x93: 0x201C, 0x94: 0x201D, 0x95: 0x2022, 0x96: 0x2013, 0x97: 0x2014,
    0x98: 0x02DC, 0x99: 0x2122, 0x9A: 0x0161, 0x9B: 0x203A, 0x9C: 0x0153,
    0x9E: 0x017E, 0x9F: 0x0178,
}


def byte_to_unicode(b):
    if 0x20 <= b <= 0x7E or b >= 0xA0:
        return b
    return WINANSI_EXTRA.get(b)


def u16(d, o):
    return struct.unpack_from(">H", d, o)[0]


def i16(d, o):
    return struct.unpack_from(">h", d, o)[0]


def u32(d, o):
    return struct.unpack_from(">I", d, o)[0]


class TTF:
    def __init__(self, path):
        self.data = open(path, "rb").read()
        self.tables = {}
        n = u16(self.data, 4)
        for i in range(n):
            o = 12 + i * 16
            tag = self.data[o:o + 4].decode("latin1")
            self.tables[tag] = (u32(self.data, o + 8), u32(self.data, o + 12))

        head = self.tables["head"][0]
        self.units_per_em = u16(self.data, head + 18)

        hhea = self.tables["hhea"][0]
        self.ascent = i16(self.data, hhea + 4)
        self.descent = i16(self.data, hhea + 6)
        self.line_gap = i16(self.data, hhea + 8)
        self.num_hmetrics = u16(self.data, hhea + 34)

        self.cap_height = 0
        if "OS/2" in self.tables:
            os2, olen = self.tables["OS/2"]
            if olen >= 90:
                self.cap_height = i16(self.data, os2 + 88)

        hmtx = self.tables["hmtx"][0]
        self.advances = [u16(self.data, hmtx + 4 * i) for i in range(self.num_hmetrics)]

        self.cmap = self._parse_cmap()

    def _parse_cmap(self):
        base = self.tables["cmap"][0]
        n = u16(self.data, base + 2)
        best = None
        for i in range(n):
            platform, encoding, off = u16(self.data, base + 4 + 8 * i), \
                u16(self.data, base + 6 + 8 * i), u32(self.data, base + 8 + 8 * i)
            fmt = u16(self.data, base + off)
            if fmt == 4 and platform == 3:
                best = base + off
                break
            if fmt == 4 and best is None:
                best = base + off
        if best is None:
            raise RuntimeError("no format-4 cmap")
        o = best
        seg_count = u16(self.data, o + 6) // 2
        end_off = o + 14
        start_off = end_off + 2 * seg_count + 2
        delta_off = start_off + 2 * seg_count
        ro_off = delta_off + 2 * seg_count

        def lookup(c):
            for s in range(seg_count):
                end = u16(self.data, end_off + 2 * s)
                if c > end:
                    continue
                start = u16(self.data, start_off + 2 * s)
                if c < start:
                    return 0
                delta = i16(self.data, delta_off + 2 * s)
                ro = u16(self.data, ro_off + 2 * s)
                if ro == 0:
                    return (c + delta) % 65536
                gi = ro_off + 2 * s + ro + 2 * (c - start)
                gid = u16(self.data, gi)
                return (gid + delta) % 65536 if gid else 0
            return 0

        return lookup

    def advance(self, uni):
        gid = self.cmap(uni)
        if gid >= self.num_hmetrics:
            gid = self.num_hmetrics - 1
        return self.advances[gid]

    def w1000(self, v):
        return round(v * 1000 / self.units_per_em)


def main():
    print("// Code generated by font/genmetrics.py; DO NOT EDIT.")
    print("// 数据来源：Liberation 字体（与标准 14 字体度量兼容），单位 1/1000 em。")
    print()
    print("package font")
    for var, path in FONTS:
        t = TTF(path)
        widths = {}
        for b in range(256):
            uni = byte_to_unicode(b)
            if uni is None:
                continue
            w = t.w1000(t.advance(uni))
            if w:
                widths[b] = w
        print()
        print(f"var {var} = Metrics{{")
        print(f"\tAscent: {t.w1000(t.ascent)}, Descent: {t.w1000(t.descent)}, "
              f"CapHeight: {t.w1000(t.cap_height)}, LineGap: {t.w1000(t.line_gap)},")
        items = [f"{b}: {w}" for b, w in sorted(widths.items())]
        print("\tWidths: [256]int32{")
        for i in range(0, len(items), 8):
            print("\t\t" + ", ".join(items[i:i + 8]) + ",")
        print("\t},")
        print("}")


if __name__ == "__main__":
    main()
