package main

import (
	"flag"
	"fmt"

	"gopkg.761sama.com/tenon-plugin-pdf"
	"gopkg.761sama.com/tenon-plugin-pdf/color"
	"gopkg.761sama.com/tenon-plugin-pdf/font"
	"gopkg.761sama.com/tenon-plugin-pdf/page"
	"gopkg.761sama.com/tenon-plugin-pdf/table"
	"gopkg.761sama.com/tenon-plugin-pdf/text"
)

// cmdTable 生成「合同样式表格」演示 PDF：采购订单，60 行内容，跨页重复表头。
func cmdTable(args []string) error {
	fs := flag.NewFlagSet("table", flag.ExitOnError)
	out := fs.String("o", "table-demo.pdf", "输出文件")
	rows := fs.Int("rows", 120, "内容行数")
	fs.Parse(args)

	doc := pdf.New()
	doc.Info().Title = "Purchase Order - Table Demo"
	doc.Info().Creator = "tenon-pdf table"
	doc.SetPageLayout(pdf.LayoutSinglePage)

	const (
		margin   = 50.0
		topY     = 640.0 // 首页表格上边缘（上方留出抬头区）
		bottomY  = 60.0
		contTopY = 790.0 // 续页表格上边缘
	)
	tableW := page.A4.W - 2*margin

	p := doc.AddPage(page.A4)

	// 抬头
	p.SetFillColor(color.Hex(0x1a3a6b))
	p.DrawText(font.HelveticaBold, 20, margin, 800, "PURCHASE ORDER")
	p.SetFillColor(color.Black)
	p.DrawText(font.Helvetica, 10, margin, 780, "PO No.: PO-2026-0904")
	p.DrawText(font.Helvetica, 10, margin, 766, "Date: 2026-09-04")
	p.DrawText(font.Helvetica, 10, 320, 780, "Vendor: ACME Industrial Supplies Ltd.")
	p.DrawText(font.Helvetica, 10, 320, 766, "Ship To: 761 Warehouse, Dock 3")
	p.SetStrokeColor(color.Hex(0x1a3a6b)).SetLineWidth(1.5)
	p.Line(margin, 754, page.A4.W-margin, 754)
	p.DrawText(font.HelveticaOblique, 9, margin, 738, "Please supply the following items in accordance with the terms and conditions of Contract No. CT-2026-081.")

	// 表格：序号、品名、规格、数量、单价、金额
	tbl := table.New(
		table.Column{Title: "No.", Width: 36, Align: text.AlignCenter},
		table.Column{Title: "Item", Width: 0}, // 自动均分
		table.Column{Title: "Specification", Width: 0},
		table.Column{Title: "Qty", Width: 44, Align: text.AlignRight},
		table.Column{Title: "Unit Price", Width: 72, Align: text.AlignRight},
		table.Column{Title: "Amount", Width: 80, Align: text.AlignRight},
	)

	items := []struct {
		name, spec string
		price      float64
	}{
		{"Hex Bolt", "M8 x 30mm, SS304", 0.12},
		{"Hex Nut", "M8, SS304", 0.08},
		{"Flat Washer", "M8, SS304", 0.03},
		{"Ball Bearing", "6204-2RS, 20x47x14mm", 2.45},
		{"Hydraulic Hose", "1/2\", 3000 PSI, 2m", 18.90},
		{"Pressure Gauge", "0-250 bar, 63mm dial", 12.75},
		{"Solenoid Valve", "24VDC, 1/4\" NPT", 34.50},
		{"PLC Module", "16DI/16DO, 24VDC", 189.00},
		{"Proximity Sensor", "M12, PNP NO, 4mm", 8.60},
		{"Cable Gland", "M20 x 1.5, IP68", 1.15},
		{"Terminal Block", "2.5mm2, DIN rail", 0.42},
		{"Circuit Breaker", "16A, 2P, C curve", 6.80},
	}
	total := 0.0
	for i := 1; i <= *rows; i++ {
		it := items[(i-1)%len(items)]
		qty := float64((i*7)%50 + 1)
		amount := qty * it.price
		total += amount
		tbl.AddRow(
			fmt.Sprintf("%d", i),
			it.name,
			it.spec,
			fmt.Sprintf("%.0f", qty),
			fmt.Sprintf("%.2f", it.price),
			fmt.Sprintf("%.2f", amount),
		)
	}
	// 合计行
	tbl.AddRow("", "TOTAL", "", "", "", fmt.Sprintf("%.2f", total))

	newPage := func() (*page.Page, float64) {
		return doc.AddPage(page.A4), contTopY
	}
	last, endY := tbl.Draw(p, margin, topY, tableW, bottomY, newPage)

	// 汇总小表：演示单元格合并（跨行/跨列）与内容自适应列宽
	if endY-160 < bottomY {
		last, endY = newPage()
	}
	last.DrawText(font.HelveticaBold, 11, margin, endY-16, "Summary (cell merge + auto column width):")
	sum := table.New(
		table.Column{Title: "Group"}, // 自适应
		table.Column{Title: "Item"},  // 自适应
		table.Column{Title: "Amount", Align: text.AlignRight},
	)
	sum.AutoWidth = true
	sum.AddRowCells(
		table.C("Goods").Span(1, 2),
		table.C("Line items subtotal"),
		table.C(fmt.Sprintf("%.2f", total)),
	)
	sum.AddRowCells(
		table.C("Packaging & delivery"),
		table.C("0.00"),
	)
	sum.AddRowCells(
		table.C("GRAND TOTAL").Span(2, 1),
		table.C(fmt.Sprintf("%.2f", total)),
	)
	_, endY = sum.Draw(last, margin, endY-26, 300, bottomY, newPage)

	// 末页落款
	last.SetFillColor(color.Black)
	last.DrawText(font.Helvetica, 10, margin, endY-30, "Authorized Signature: ______________________")
	last.DrawText(font.Helvetica, 10, 320, endY-30, "Date: ______________________")
	last.DrawText(font.HelveticaOblique, 8, margin, endY-50,
		"Generated by tenon-pdf table — header repeats on every page break.")

	return doc.SaveFile(*out)
}
